### PR TITLE
Add Travis build

### PR DESCRIPTION
**Pull request by asbjornu**
Adds Travis building to the repository.

### CODE REVIEW

**Comment by asbjornu** [comment]
Someone should turn on the build knob for the [NUnit.System.Linq project on Travis](https://travis-ci.org/nunit/NUnit.System.Linq) when this is merged, so I can have #6 built on Linux as well.

**Comment by rprouse** [comment]
I turned on the Travis build for this repo. Can you push a non-change to trigger a build? A `git commit --amend; git push -f` will do the trick.

**Comment by asbjornu** [comment]
@rprouse There we go! :+1:

**Comment by rprouse** [comment]
Awesome, GREEN for the win! :+1:

**Pull request merged**
